import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import api, { serverUrl } from '../services/api';
import { useAuth } from '../context/AuthContext';
import Notification from '../components/Notification';
import Loader from '../components/Loader';

export default function EventDetails() {
  const { id } = useParams(); const { user } = useAuth(); const [event, setEvent] = useState(); const [comments, setComments] = useState([]); const [text, setText] = useState(''); const [message, setMessage] = useState(''); const [feedback, setFeedback] = useState({ rating: 5, comment: '' });
  const load = () => { api.get(`/events/${id}`).then((response) => setEvent(response.data)); api.get(`/comments/${id}`).then((response) => setComments(response.data)); };
  useEffect(load, [id]); if (!event) return <Loader/>;
  const register = async () => { try { await api.post(`/registrations/${id}`); setMessage('You are registered. A confirmation was added to your notifications.'); } catch (error) { setMessage(error.response?.data?.message); } };
  const comment = async (item) => { item.preventDefault(); try { await api.post(`/comments/${id}`, { text }); setText(''); load(); } catch (error) { setMessage(error.response?.data?.message); } };
  const sendFeedback = async (item) => { item.preventDefault(); try { await api.post(`/feedback/${id}`, feedback); setMessage('Thank you for your private feedback.'); setFeedback({ rating: 5, comment: '' }); } catch (error) { setMessage(error.response?.data?.message || 'Feedback could not be submitted.'); } };
  const eventEnded = event.date <= new Date().toISOString().slice(0, 10);
  return <div className="mx-auto max-w-3xl"><div className="overflow-hidden rounded-xl bg-white shadow">{event.image && <img className="h-64 w-full object-cover" src={serverUrl(event.image)} alt=""/>}<div className="p-7"><p className="text-indigo-700">{event.category}</p><h1 className="text-3xl font-bold">{event.title}</h1><p className="mt-3 text-slate-600">{event.date} at {event.time} · {event.location}</p><p className="mt-5 whitespace-pre-wrap">{event.description}</p><p className="mt-4 text-sm text-slate-500">Hosted by {event.organizer} · {event.registrationCount}/{event.capacity || '∞'} registered</p><div className="mt-6 flex gap-3">{user?.role === 'student' && <button className="btn" onClick={register}>Register</button>}<a className="btn-secondary" href={`${serverUrl()}/api/events/${id}/calendar`}>Add to calendar</a></div><Notification error={message}/></div></div>
    {user?.role === 'student' && eventEnded && <section className="mt-8 rounded-xl bg-white p-6 shadow"><h2 className="text-xl font-bold">How was the event?</h2><p className="mt-1 text-sm text-slate-500">Your feedback is private and visible only to the organizer.</p><form className="mt-4" onSubmit={sendFeedback}><label>Rating<select className="input mt-1" value={feedback.rating} onChange={(item) => setFeedback({ ...feedback, rating: Number(item.target.value) })}>{[5,4,3,2,1].map((rating) => <option key={rating} value={rating}>{rating} star{rating !== 1 ? 's' : ''}</option>)}</select></label><label className="mt-3 block">Comment (optional)<textarea className="input mt-1 min-h-24" value={feedback.comment} onChange={(item) => setFeedback({ ...feedback, comment: item.target.value })}/></label><button className="btn mt-4">Submit feedback</button></form></section>}
    <section className="mt-8"><h2 className="text-xl font-bold">Discussion</h2>{user && <form onSubmit={comment} className="mt-3 flex gap-2"><input className="input" value={text} onChange={(item) => setText(item.target.value)} placeholder="Ask a question or leave a comment"/><button className="btn">Post</button></form>}<div className="mt-4 space-y-3">{comments.map((item) => <div className="rounded bg-white p-3 shadow-sm" key={item.id}><b>{item.author}</b><p>{item.text}</p></div>)}</div></section></div>;
}
