import { Router } from 'express';
import { readData, writeData } from '../utils/fileHandler.js';
import { generateId } from '../utils/generateId.js';
import { authenticate } from '../middleware/authMiddleware.js';
import { allowRoles } from '../middleware/roleMiddleware.js';
import { notifyMany } from '../utils/notifications.js';

const router = Router();
const publicEvents = (events, clubId) => events.filter((event) => event.clubId === clubId && (event.status || 'published') === 'published' && (event.approvalStatus || 'approved') === 'approved');
const detail = async (club, userId = '') => { const [users, events, follows, announcements] = await Promise.all(['users.json', 'events.json', 'follows.json', 'announcements.json'].map(readData)); const members = follows.filter((follow) => follow.clubId === club.id); return { ...club, owner: users.find((user) => user.id === club.ownerId)?.name || '', memberCount: members.length, following: Boolean(userId && members.some((follow) => follow.userId === userId)), upcomingEvents: publicEvents(events, club.id).filter((event) => event.date >= new Date().toISOString().slice(0, 10)).sort((a, b) => `${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)), announcements: announcements.filter((item) => item.clubId === club.id).sort((a, b) => b.createdAt.localeCompare(a.createdAt)) }; };

router.get('/', async (_, res) => { const clubs = await readData('clubs.json'); res.json(await Promise.all(clubs.map((club) => detail(club)))); });
router.get('/:id', async (req, res) => { const club = (await readData('clubs.json')).find((item) => item.id === req.params.id); if (!club) return res.status(404).json({ message: 'Club not found.' }); res.json(await detail(club)); });
router.get('/:id/me', authenticate, async (req, res) => { const club = (await readData('clubs.json')).find((item) => item.id === req.params.id); if (!club) return res.status(404).json({ message: 'Club not found.' }); res.json(await detail(club, req.user.id)); });
router.post('/:id/follow', authenticate, allowRoles('student'), async (req, res) => { const clubs = await readData('clubs.json'); if (!clubs.some((club) => club.id === req.params.id)) return res.status(404).json({ message: 'Club not found.' }); const follows = await readData('follows.json'); if (follows.some((follow) => follow.clubId === req.params.id && follow.userId === req.user.id)) return res.status(409).json({ message: 'You already follow this club.' }); follows.push({ id: generateId('follow'), clubId: req.params.id, userId: req.user.id, createdAt: new Date().toISOString() }); await writeData('follows.json', follows); res.status(201).json({ following: true }); });
router.delete('/:id/follow', authenticate, async (req, res) => { const follows = await readData('follows.json'); const exists = follows.some((follow) => follow.clubId === req.params.id && follow.userId === req.user.id); if (!exists) return res.status(404).json({ message: 'You do not follow this club.' }); await writeData('follows.json', follows.filter((follow) => !(follow.clubId === req.params.id && follow.userId === req.user.id))); res.status(204).end(); });
router.post('/:id/announcements', authenticate, allowRoles('organizer', 'admin'), async (req, res) => { const clubs = await readData('clubs.json'); const club = clubs.find((item) => item.id === req.params.id); if (!club) return res.status(404).json({ message: 'Club not found.' }); if (req.user.role !== 'admin' && club.ownerId !== req.user.id) return res.status(403).json({ message: 'Only the club owner can post announcements.' }); const message = req.body.message?.trim(); if (!message) return res.status(400).json({ message: 'Announcement text is required.' }); const announcements = await readData('announcements.json'); const announcement = { id: generateId('announcement'), clubId: club.id, message, createdAt: new Date().toISOString() }; announcements.push(announcement); await writeData('announcements.json', announcements); const followers = (await readData('follows.json')).filter((follow) => follow.clubId === club.id).map((follow) => follow.userId); await notifyMany(followers, `${club.name}: ${message}`, 'club_announcement', `/clubs/${club.id}`); res.status(201).json(announcement); });
export default router;
