import { Router } from 'express';
import { readData, writeData } from '../utils/fileHandler.js';
import { generateId } from '../utils/generateId.js';
import { authenticate } from '../middleware/authMiddleware.js';
import { allowRoles } from '../middleware/roleMiddleware.js';
const router = Router();
router.post('/:eventId', authenticate, allowRoles('student'), async (req, res) => { const rating = Number(req.body.rating); const comment = req.body.comment?.trim() || ''; if (!Number.isInteger(rating) || rating < 1 || rating > 5) return res.status(400).json({ message: 'Choose a rating from 1 to 5.' }); const [events, registrations, feedback] = await Promise.all(['events.json', 'registrations.json', 'feedback.json'].map(readData)); const event = events.find((item) => item.id === req.params.eventId); if (!event) return res.status(404).json({ message: 'Event not found.' }); if (event.date > new Date().toISOString().slice(0, 10)) return res.status(400).json({ message: 'Feedback opens after the event date.' }); if (!registrations.some((registration) => registration.eventId === event.id && registration.userId === req.user.id)) return res.status(403).json({ message: 'Only registered attendees can leave feedback.' }); if (feedback.some((item) => item.eventId === event.id && item.userId === req.user.id)) return res.status(409).json({ message: 'You have already submitted feedback.' }); const item = { id: generateId('feedback'), eventId: event.id, userId: req.user.id, rating, comment, createdAt: new Date().toISOString() }; feedback.push(item); await writeData('feedback.json', feedback); res.status(201).json(item); });
router.get('/event/:eventId', authenticate, allowRoles('organizer', 'admin'), async (req, res) => { const events = await readData('events.json'); const event = events.find((item) => item.id === req.params.eventId); if (!event) return res.status(404).json({ message: 'Event not found.' }); if (req.user.role !== 'admin' && event.organizerId !== req.user.id) return res.status(403).json({ message: 'Not permitted.' }); const feedback = (await readData('feedback.json')).filter((item) => item.eventId === event.id); const averageRating = feedback.length ? Number((feedback.reduce((sum, item) => sum + item.rating, 0) / feedback.length).toFixed(1)) : 0; res.json({ eventId: event.id, responseCount: feedback.length, averageRating, ratings: [1,2,3,4,5].map((rating) => ({ rating, count: feedback.filter((item) => item.rating === rating).length })), comments: feedback.filter((item) => item.comment).map(({ rating, comment, createdAt }) => ({ rating, comment, createdAt })) }); });
export default router;
